### ISSUE TITLE
Add the test procedures to the Specifications released directories

### ISSUE THREAD

**Issue by joseph-mueller** [LxiStandard/LxiStandard.github.io#24]
Do this in SharePoint and they will propagate to web.

**Comment by jryland59** [comment]
In SharePoint called LXI_TestProcedures_DRAFT_1.6_2023-10-20.pdf
Only pdf version
Located here: https://lxistandard.sharepoint.com/:b:/r/Shared%20Documents/Technical%20Committee/Specifications/Released/LXI%202023%20Revision%201.6/[LXI_TestProcedures_DRAFT_1.6_2023-10-20.pdf](https://lxistandard.sharepoint.com/:b:/r/Shared%20Documents/Technical%20Committee/Specifications/Released/LXI%202023%20Revision%201.6/LXI_TestProcedures_DRAFT_1.6_2023-10-20.pdf?csf=1&web=1&e=JmroF8)?csf=1&web=1&e=JmroF8

**Comment by jryland59** [comment]
draft version only needs Lxi logo and TSEP to say its all up to date which it probably is not as they are still coding Reference Design and Kerberos
